# Generated by Django 4.2.7 on 2025-06-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDocente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=100)),
                ('grado_academico', models.CharField(max_length=50)),
                ('departamento_asignado', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimEstudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('programa_academico', models.CharField(max_length=100)),
                ('semestre_ingreso', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimMateria',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=150)),
                ('creditos', models.IntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPrograma',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=150)),
                ('nivel', models.CharField(max_length=50)),
                ('coordinador', models.CharField(blank=True, max_length=100, null=True)),
                ('facultad', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_programa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTiempo',
            fields=[
                ('id_tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('periodo', models.CharField(max_length=10)),
                ('mes_inicio', models.IntegerField()),
                ('mes_fin', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dim_tiempo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HechosRendimientoAcademico',
            fields=[
                ('id_hecho', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estatus', models.CharField(max_length=20)),
                ('creditos_obtenidos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hechos_rendimiento_academico',
                'managed': False,
            },
        ),
    ]
