services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: datawarehouse_db
    environment:
      POSTGRES_DB: datawarehouse
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - dw_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dw_user -d datawarehouse"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Django con OLAP
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: datawarehouse_backend
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://dw_user:dw_password@db:5432/datawarehouse
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
      - ./olap:/app/olap
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dw_network
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

  # Frontend con interfaz OLAP
  frontend:
    image: nginx:alpine
    container_name: datawarehouse_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dw_network

  # Servicio de análisis OLAP (opcional para procesamiento pesado)
  olap_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: datawarehouse_olap
    environment:
      - DATABASE_URL=postgresql://dw_user:dw_password@db:5432/datawarehouse
      - OLAP_MODE=1
    volumes:
      - ./olap:/app/olap
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dw_network
    command: >
      sh -c "
        echo 'Servicio OLAP iniciado' &&
        tail -f /dev/null
      "

volumes:
  postgres_data:
    driver: local

networks:
  dw_network:
    driver: bridge
